name: CI-Backend

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
jobs:
  before-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: cd starter/backend && pip install pipenv
    - run: cd starter/backend && pipenv install
    - run: cd starter/backend && pipenv run test
    - run: cd starter/backend && timeout 20s pipenv run serve

  build:
    runs-on: ubuntu-latest
    needs: before-build
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: cd starter/backend && pip install pipenv
    - run: cd starter/backend && pipenv install
    - run: cd starter/backend && timeout 20s pipenv run serve


