name: frontend-CI

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
jobs:
  before-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd starter/frontend && npm i -g
    - run: cd starter/frontend && npm test
    - run: cd starter/frontend && npm run lint

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    needs: before-build
    steps:
    - run: |
        cd starter/frontend && npm run build
        echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."


